name: Update gist with WakaTime stats
on:
  schedule:
    - cron: "0 0 * * *"
  # Manual triggers with workflow_dispatch
  workflow_dispatch:
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Check WakaTime API (temporary)
        run: |
          code=$(curl -s -o /dev/null -w "%{http_code}" \
            "https://wakatime.com/api/v1/users/current/stats/last_7_days?api_key=$WAKATIME_API_KEY")
          echo "WakaTime API status: $code"
        env:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
