name: Update gist with WakaTime stats
on:
  schedule:
    - cron: "0 0 * * *"
  # Manual triggers with workflow_dispatch
  workflow_dispatch:
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Debug write to Gist (temporary)
        run: |
          echo '{"description":"debug","files":{"waka":{"content":"hello from action"}}}' > body.json
          curl -s -X PATCH \
            -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/gists/$GIST_ID \
            -d @body.json
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID:  ${{ secrets.GIST_ID }}



